name: flutter_easy_setup
description: Flutter Easy Setup!
version: 1.0.0
 #repository: https://github.com/Ag1rin/flutter_easy_setup

environment:
  sdk: ^3.9.2


dependencies:
  path: ^1.9.0
  args: ^2.7.0
  process_run: ^1.2.4
  http: ^1.6.0
  dartz: ^0.10.1
  ansicolor: ^2.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  fes: main